# Example configuration file for ML Agent
# Save this as config.yaml and use --config config.yaml when starting the agent

agent_name: "MyMLAgent"
log_level: "INFO"
log_file: "ml_agent.log"

# Resource management
max_gpu_memory: 8.0  # GB
max_cpu_memory: 16.0  # GB
enable_memory_optimization: true
enable_model_caching: true

# API settings
api_host: "0.0.0.0"
api_port: 8000
api_workers: 4
enable_cors: true

# Monitoring
enable_monitoring: true
metrics_port: 8001
health_check_interval: 30

# Model configurations
models:
  gpt2:
    name: "GPT-2"
    model_type: "text"
    model_path: "gpt2"
    device: "auto"
    max_memory: 2.0
    precision: "float16"
    batch_size: 1
    max_length: 100
    temperature: 0.7
    top_p: 0.9
    top_k: 50
    parameters: {}
  
  stable_diffusion:
    name: "Stable Diffusion"
    model_type: "image"
    model_path: "runwayml/stable-diffusion-v1-5"
    device: "auto"
    max_memory: 4.0
    precision: "float16"
    batch_size: 1
    parameters:
      enable_attention_slicing: true
      enable_vae_slicing: true
  
  qwen_vl:
    name: "Qwen-VL"
    model_type: "multimodal"
    model_path: "Qwen/Qwen-VL-Chat"
    device: "auto"
    max_memory: 6.0
    precision: "float16"
    batch_size: 1
    parameters: {}

# Task configurations
tasks:
  text_generation:
    name: "Text Generation"
    task_type: "text_generation"
    model_name: "gpt2"
    input_format: "text"
    output_format: "text"
    timeout: 60
    retry_attempts: 3
    batch_processing: false
    max_batch_size: 1
    parameters: {}
  
  image_generation:
    name: "Image Generation"
    task_type: "image_generation"
    model_name: "stable_diffusion"
    input_format: "text"
    output_format: "image"
    timeout: 300
    retry_attempts: 3
    batch_processing: false
    max_batch_size: 1
    parameters:
      default_width: 512
      default_height: 512
      default_steps: 50
  
  classification:
    name: "Classification"
    task_type: "classification"
    model_name: "qwen_vl"
    input_format: "multimodal"
    output_format: "text"
    timeout: 120
    retry_attempts: 3
    batch_processing: true
    max_batch_size: 4
    parameters: {}
